nexus_dict = {
	"strandeddeep" : {
		"2": "Miscellaneous"
	},
	"lobotomycorporation" : {
		"2": "Miscellaneous", 
		"3": "Equipment Pack", 
		"4": "Tools and Utilities"
	},
	"minecraft" : {
		"10": "Maps - Miscellaneous", 
		"11": "Player Skins", 
		"13": "Minigames", 
		"14": "Maps - Survival", 
		"15": "Weapons and Tools", 
		"16": "Biomes", 
		"17": "Food", 
		"18": "Miscellaneous Items", 
		"19": "Crafting", 
		"2": "Miscellaneous", 
		"20": "Armour", 
		"3": "Resource/Texture pack", 
		"4": "Maps - Adventure", 
		"5": "World Save", 
		"6": "Maps - Challenge", 
		"8": "NPCs and Creatures"
	},
	"pcbuildingsimulator" : {
		"2": "Miscellaneous"
	},
	"mytimeatportia" : {
		"2": "Miscellaneous", 
		"3": "Gameplay Effects and Changes", 
		"4": "User Interface", 
		"5": "Visuals and Graphics", 
		"6": "Audio"
	},
	"thesims3" : {
		"2": "Miscellaneous", 
		"3": "Decor", 
		"4": "Hair", 
		"5": "Sims", 
		"6": "Clothing", 
		"7": "Gameplay"
	},
	"banished" : {
		"10": "Translations", 
		"11": "Models and Textures", 
		"12": "Utilities", 
		"2": "Miscellaneous", 
		"3": "Gameplay", 
		"4": "Audio - Sounds", 
		"5": "Audio - Music", 
		"6": "Buildings/Constructions", 
		"7": "Fixes/Tweaks", 
		"8": "User Interface", 
		"9": "Terrain"
	},
	"planetexplorers" : {
		"10": "ISO - Water Vehicles", 
		"11": "ISO - Objects", 
		"12": "ISO - Buildings &amp; Colony", 
		"2": "Miscellaneous", 
		"4": "ISO - Guns", 
		"5": "ISO - Swords", 
		"6": "ISO - Energy Weapons", 
		"7": "ISO - Shields", 
		"8": "ISO - Ground Vehicles", 
		"9": "ISO - Air Vehicles"
	},
	"gtasanandreas" : {
		"18": "Aircraft", 
		"19": "Alfa Romeo", 
		"2": "Miscellaneous", 
		"20": "AMC", 
		"21": "Aston Martin", 
		"22": "Audi", 
		"23": "Bentley", 
		"24": "Bikes", 
		"3": "Weapons", 
		"30": "BMW", 
		"31": "Boats", 
		"32": "Bugatti", 
		"33": "Buick", 
		"34": "Cadillac", 
		"35": "Chevrolet", 
		"36": "Chrysler", 
		"37": "Citroen", 
		"38": "Daewoo", 
		"39": "Delorean", 
		"4": "Bikes", 
		"40": "Dodge", 
		"41": "Ferrari", 
		"42": "Fiat", 
		"43": "Ford", 
		"44": "Holden", 
		"45": "Honda", 
		"46": "Hummer", 
		"47": "Hyundai", 
		"48": "Jaguar", 
		"49": "Koenigsegg", 
		"5": "Boats", 
		"50": "Lada", 
		"51": "Lamborghini", 
		"52": "Lancia", 
		"53": "Land Rover", 
		"54": "Lexus", 
		"55": "Lotus", 
		"56": "Maserati", 
		"57": "Mercedes Benz", 
		"58": "Nissan", 
		"59": "Other", 
		"6": "Clothing", 
		"67": "Pagani", 
		"68": "Peugeot", 
		"69": "Plymouth", 
		"70": "Porsche", 
		"71": "Seat", 
		"72": "Spyker Cars", 
		"73": "Toyota", 
		"74": "Vehicle Packs"
	},
	"zootycoon2" : {
		"10": "Maps", 
		"11": "Gameplay Effects and Changes", 
		"12": "Objects", 
		"13": "Staff", 
		"2": "Miscellaneous", 
		"3": "Animals", 
		"4": "Landscaping", 
		"5": "Expansions", 
		"8": "Ambients", 
		"9": "Visual Presets"
	},
	"shadowofthetombraider" : {
		"2": "Miscellaneous", 
		"3": "Reshade"
	},
	"farcry5" : {
		"2": "Miscellaneous"
	},
	"hitman2" : {
		"2": "Miscellaneous"
	},
	"assassinscreedorigins" : {
		"10": "Saved Games", 
		"2": "Miscellaneous", 
		"4": "Outfits", 
		"5": "User Interface", 
		"6": "Visuals and Graphics", 
		"7": "Modders Resources and Tutorials", 
		"8": "Utilities", 
		"9": "Body, Face and Hair"
	},
	"grimdawn" : {
		"2": "Miscellaneous", 
		"3": "Visuals and Graphics", 
		"4": "Utilities"
	},
	"elex" : {
		"2": "Miscellaneous"
	},
	"subnauticabelowzero" : {
		"10": "Gameplay Effects and Changes", 
		"11": "Library", 
		"12": "Environment", 
		"13": "Adventure", 
		"14": "ModLoader", 
		"15": "Vehicles and Upgrades", 
		"2": "Miscellaneous", 
		"3": "Shader Presets", 
		"4": "Utilities", 
		"5": "User Interface", 
		"6": "Bug Fixes", 
		"7": "Save Games", 
		"8": "Base Pieces", 
		"9": "Items"
	},
	"wasteland2" : {
		"2": "Miscellaneous", 
		"3": "Gameplay", 
		"4": "Portraits", 
		"5": "Translations", 
		"6": "User Interface", 
		"7": "Utilities", 
		"8": "Characters", 
		"9": "Models and Textures"
	},
	"batmanarkhamknight" : {
		"2": "Miscellaneous", 
		"3": "Saved games"
	},
	"watchdogs" : {
		"10": "Models and Textures", 
		"2": "Miscellaneous", 
		"3": "Clothing", 
		"4": "Visuals and Graphics", 
		"5": "User Interface", 
		"9": "Utilities"
	},
	"jadeempire" : {
		"2": "Miscellaneous", 
		"3": "Companions", 
		"4": "Gameplay Effects and Changes", 
		"5": "Models and textures", 
		"6": "Player Character", 
		"7": "Utilities", 
		"8": "Styles", 
		"9": "Audio"
	},
	"farcry4" : {
		"10": "Utilities", 
		"11": "Weapons", 
		"12": "Visuals and Graphics", 
		"13": "Saved games", 
		"2": "Miscellaneous", 
		"3": "User Interface", 
		"4": "Models and Textures", 
		"5": "Maps", 
		"6": "AI", 
		"7": "Bug Fixes", 
		"8": "Configs", 
		"9": "Crafting"
	},
	"dragonballzkakarot" : {
		"2": "Miscellaneous", 
		"3": "Audio", 
		"4": "User Interface", 
		"5": "Gameplay Effects and Changes", 
		"6": "Visuals and Graphics"
	},
	"stellaris" : {
		"10": "Military - Ships, Armies, Stations", 
		"11": "Buildings and Megastructures", 
		"12": "Balancing and Fixes", 
		"13": "Cheats", 
		"14": "Modders Resources and Tutorials", 
		"15": "Visuals and Graphics", 
		"16": "User Interface", 
		"2": "Miscellaneous", 
		"3": "Audio", 
		"5": "Gameplay Effects and Changes", 
		"6": "Galaxy Generation", 
		"7": "Technologies", 
		"8": "Species, Traits, and Portraits", 
		"9": "Empires"
	},
	"prey2017" : {
		"2": "Miscellaneous"
	},
	"vermintide" : {
		"2": "Miscellaneous"
	},
	"empyriongalacticsurvival" : {
		"2": "Miscellaneous"
	},
	"masteroforionconquerthestars" : {
		"2": "Miscellaneous"
	},
	"space" : {
		"2": "Miscellaneous"
	},
	"theouterworlds" : {
		"10": "Modders Resources and Tutorials", 
		"11": "Utilities", 
		"12": "Models and Textures", 
		"13": "Cheats and God items", 
		"2": "Miscellaneous", 
		"4": "Save Games", 
		"5": "User Interface", 
		"6": "Gameplay Effects and Changes", 
		"7": "Audio", 
		"8": "Animation", 
		"9": "Visuals and Graphics"
	},
	"stateofdecay2" : {
		"4": "Miscellaneous", 
		"5": "Buildings and Facilities", 
		"6": "Weapons", 
		"7": "Spawns", 
		"8": "Gameplay"
	},
	"needforspeedpayback" : {
		"11": "New Vehicles", 
		"2": "Miscellaneous", 
		"3": "Car Modifications", 
		"4": "Gameplay Effects and Changes", 
		"5": "Visuals and Graphics", 
		"6": "User Interface", 
		"7": "Models and Textures", 
		"8": "Cheats", 
		"9": "Audio"
	},
	"gta4" : {
		"2": "Miscellaneous", 
		"3": "Vehicle Textures", 
		"4": "Scripts", 
		"5": "Models and Textures", 
		"6": "Utilities", 
		"7": "Saved games", 
		"8": "Audio - Misc"
	},
	"yakuzakiwami2" : {
		"2": "Miscellaneous", 
		"3": "Characters", 
		"4": "Combat", 
		"5": "Weapons", 
		"6": "Audio"
	},
	"nierautomata" : {
		"2": "Miscellaneous"
	},
	"anno1800" : {
		"10": "Ornaments", 
		"11": "Utilities", 
		"2": "Miscellaneous", 
		"3": "Cheats", 
		"4": "Gameplay Effects and Changes", 
		"5": "Visuals and Graphics", 
		"6": "Audio", 
		"7": "User Interface", 
		"8": "Ships", 
		"9": "Buildings"
	},
	"astroximperium" : {
		"2": "Miscellaneous", 
		"4": "Ships"
	},
	"crusaderkings2" : {
		"2": "Miscellaneous", 
		"3": "Overhauls", 
		"4": "Custom Characters", 
		"5": "Traits", 
		"6": "Tweaks", 
		"7": "Culture and Religion", 
		"8": "Visuals and Graphics", 
		"9": "User Interface"
	},
	"terraria" : {
		"2": "Miscellaneous"
	},
	"mbwithfireandsword" : {
		"24": "Modules", 
		"29": "Items", 
		"42": "Scenes and Maps", 
		"43": "Utilities", 
		"44": "Audio", 
		"46": "Miscellaneous", 
		"47": "Visuals and Graphics", 
		"48": "User Interface"
	},
	"mafia3" : {
		"2": "Miscellaneous"
	},
	"unrealtournament2004" : {
		"26": "Models", 
		"37": "Modifications", 
		"4": "Maps", 
		"42": "Mutators", 
		"56": "Skins", 
		"74": "Utilities"
	},
	"redfactionguerilla" : {
		"2": "Miscellaneous", 
		"5": "Utilities", 
		"6": "Overhauls", 
		"7": "Tweaks &amp; Fixes"
	},
	"dragonballxenoverse" : {
		"2": "Miscellaneous", 
		"3": "Hair", 
		"4": "SweetFX Preset", 
		"5": "Sound and music", 
		"6": "Costumes"
	},
	"soulcaliburvi" : {
		"2": "Miscellaneous", 
		"3": "Models", 
		"4": "Characters"
	},
	"doometernal" : {
		"2": "Miscellaneous", 
		"3": "Visuals and Graphics", 
		"4": "Maps", 
		"5": "Utilities"
	},
	"planetbase" : {
		"2": "Miscellaneous", 
		"3": "Gameplay"
	},
	"devilmaycry4" : {
		"2": "Miscellaneous", 
		"3": "Combat"
	},
	"eurotrucksimulator2" : {
		"10": "Paint Jobs", 
		"2": "Miscellaneous", 
		"3": "Trucks", 
		"4": "Visuals and graphics", 
		"5": "Maps", 
		"6": "Economy", 
		"7": "Utilities", 
		"9": "Trailers"
	},
	"mortalkombatx" : {
		"2": "Miscellaneous"
	},
	"wolcenlordsofmayhem" : {
		"10": "Audio", 
		"4": "Miscellaneous", 
		"5": "Weapons", 
		"6": "Visuals and Graphics", 
		"7": "Gameplay Effects and Changes", 
		"8": "User Interface", 
		"9": "Characters"
	},
	"batmanarkhamasylum" : {
		"2": "Miscellaneous"
	},
	"gamedevtycoon" : {
		"2": "Miscellaneous", 
		"3": "New Consoles", 
		"4": "Gameplay Changes", 
		"5": "Overhauls"
	},
	"nehrim" : {
		"2": "Miscellaneous", 
		"3": "Armour", 
		"4": "Tools and Utilities"
	},
	"starsector" : {
		"2": "Miscellaneous", 
		"3": "Utilities", 
		"4": "Factions", 
		"5": "Overhauls"
	},
	"generationzero" : {
		"2": "Miscellaneous"
	},
	"istaria" : {
		"2": "Miscellaneous"
	},
	"tekken7" : {
		"2": "Miscellaneous", 
		"3": "Characters", 
		"4": "Stages"
	},
	"evilgenius" : {
		"2": "Miscellaneous", 
		"3": "Items", 
		"4": "Gameplay Effects and Changes"
	},
	"guiltygearxrd" : {
		"2": "Miscellaneous", 
		"3": "Palettes", 
		"4": "User Interface", 
		"5": "Performance", 
		"6": "Stages", 
		"7": "Visuals and Graphics"
	},
	"baldursgate2ee" : {
		"2": "Miscellaneous", 
		"3": "Portraits", 
		"4": "Sounds and music"
	},
	"sinsofasolarempire" : {
		"10": "Utilities", 
		"13": "1.02", 
		"14": "1.03", 
		"15": "1.04", 
		"16": "1.05", 
		"20": "Large", 
		"21": "Medium", 
		"22": "Scenarios", 
		"23": "Small", 
		"3": "Miscellaneous", 
		"4": "Maps", 
		"5": "Overhauls", 
		"6": "Audio", 
		"8": "Visuals and Graphics", 
		"9": "User Interface"
	},
	"dungeondefenders" : {
		"10": "Maps - New", 
		"11": "Maps - Modified", 
		"12": "Armour - Cheat/God items", 
		"13": "Weapons - Cheat/God items", 
		"14": "Utilities", 
		"15": "Miscellaneous", 
		"16": "Bug fixes", 
		"17": "Balancing", 
		"18": "User interfaces", 
		"19": "Total conversions", 
		"2": "Weapons", 
		"4": "Armour", 
		"5": "Classes - New", 
		"6": "Classes - Modified", 
		"7": "Towers - New", 
		"8": "Towers - Modified", 
		"9": "Skins and retextures"
	},
	"phoenixpoint" : {
		"2": "Miscellaneous", 
		"3": "Gameplay Effects and Changes", 
		"4": "Cheats", 
		"5": "User Interface", 
		"6": "Visuals and Graphics"
	},
	"hades" : {
		"2": "Miscellaneous"
	},
	"ageofwonders3" : {
		"2": "Miscellaneous", 
		"3": "Overhauls", 
		"4": "Units", 
		"5": "Gameplay", 
		"6": "Visuals and Graphics", 
		"7": "Spells"
	},
	"shadowrunhongkong" : {
		"10": "Sounds and Music", 
		"11": "Stories", 
		"12": "Textures and Meshes", 
		"13": "Tilesets", 
		"14": "Tools", 
		"15": "Tutorial", 
		"16": "UI Mods", 
		"17": "Vehicles", 
		"18": "Visuals and Graphics", 
		"2": "Miscellaneous", 
		"3": "Alphas, Betas or Unfinished Work", 
		"4": "Campaign/UGC", 
		"5": "Cheats", 
		"6": "Items", 
		"7": "Maps", 
		"8": "Portraits", 
		"9": "Props and Scene Assets"
	},
	"projectzomboid" : {
		"2": "Miscellaneous", 
		"3": "Items", 
		"4": "Gameplay", 
		"5": "Maps", 
		"6": "Weapons", 
		"7": "Skins"
	},
	"wargroove" : {
		"2": "Miscellaneous"
	},
	"shenmue" : {
		"2": "Miscellaneous", 
		"3": "Textures", 
		"4": "Reshade Presets", 
		"5": "Audio", 
		"6": "Tools and Utilities"
	},
	"deadspace2" : {
		"2": "Miscellaneous"
	},
	"blockland" : {
		"2": "Miscellaneous", 
		"3": "Bricks", 
		"4": "Prints", 
		"5": "Scripts"
	},
	"skyrim" : {
		"100": "Crafting", 
		"101": "Mounts", 
		"102": "Clothing - Jewelry", 
		"103": "Armour - Shields", 
		"104": "Shouts", 
		"106": "Enderal: Miscellaneous", 
		"107": "Enderal: Player Homes", 
		"108": "Enderal: Cheats and God items", 
		"109": "Enderal: User Interface", 
		"110": "Enderal: Bug Fixes", 
		"111": "Enderal: Armour", 
		"112": "Enderal: Weapons", 
		"113": "Enderal: Spells &amp; Enchantments", 
		"114": "Character Presets", 
		"115": "Audio", 
		"22": "Buildings", 
		"24": "Gameplay Effects and Changes", 
		"25": "Guilds/Factions", 
		"26": "Body, Face, and Hair", 
		"27": "Items and Objects - Player", 
		"28": "Miscellaneous", 
		"29": "Models and Textures", 
		"30": "New Lands", 
		"33": "NPC", 
		"34": "Races, Classes, and Birthsigns", 
		"35": "Quests and Adventures", 
		"36": "Weapons and Armour", 
		"39": "Utilities", 
		"40": "Cheats and God items", 
		"42": "User Interface", 
		"43": "Save Games", 
		"45": "Videos and Trailers", 
		"51": "Animation", 
		"53": "Cities, Towns, Villages, and Hamlets", 
		"54": "Armour", 
		"55": "Weapons", 
		"58": "Landscape Changes", 
		"60": "Clothing", 
		"61": "Audio - SFX, Music, and Voice", 
		"62": "Visuals and Graphics", 
		"67": "Player homes", 
		"68": "Castles, Palaces, Mansions, and Estates", 
		"69": "Mercantiles (shops, stores, inns, taverns, etc)",
		"70": "Forts, Ruins, and Abandoned Structures", 
		"73": "Skills and Leveling", 
		"74": "Environmental", 
		"75": "Magic - Spells &amp; Enchantments", 
		"76": "Stealth", 
		"77": "Combat", 
		"78": "Immersion", 
		"79": "Overhauls", 
		"82": "Modders Resources and Tutorials", 
		"83": "Creatures", 
		"84": "Patches", 
		"85": "Items and Objects - World", 
		"88": "Dungeons - New", 
		"89": "Locations - New", 
		"90": "Locations - Vanilla", 
		"91": "Dungeons - Vanilla", 
		"92": "Collectables, Treasure Hunts, and Puzzles", 
		"93": "Magic - Gameplay", 
		"94": "Alchemy", 
		"95": "Bug Fixes", 
		"96": "Followers and Companions", 
		"97": "ENB Preset", 
		"98": "Books and Scrolls", 
		"99": "NPC - Children"
	},
	"fallout4" : {
		"10": "Collectibles, Treasure Hunts, and Puzzles", 
		"11": "Companions", 
		"12": "Creatures", 
		"13": "ENB Presets", 
		"14": "Environment", 
		"15": "Gameplay Effects and Changes", 
		"16": "Factions", 
		"17": "Body, Face, and Hair", 
		"18": "Modders Resources and Tutorials", 
		"19": "Models and Textures", 
		"2": "Miscellaneous", 
		"20": "New Lands", 
		"21": "Locations - New", 
		"22": "NPC", 
		"23": "NPC - Vendors", 
		"24": "Overhauls", 
		"25": "Patches", 
		"26": "Performance", 
		"27": "Perks", 
		"28": "Player Homes", 
		"29": "Poses", 
		"3": "Ammo", 
		"30": "Quests and Adventures", 
		"31": "Radio", 
		"32": "Saved Games", 
		"33": "Audio - SFX", 
		"34": "Audio - Music", 
		"35": "Audio - Misc", 
		"36": "Audio - Voice", 
		"37": "User Interface", 
		"38": "Utilities", 
		"39": "Vehicles", 
		"4": "Animation", 
		"40": "Visuals and Graphics", 
		"41": "Weapons", 
		"42": "Weapons and Armour", 
		"43": "Items (Food, Drinks, Chems, etc)",
		"44": "Crafting - Equipment", 
		"45": "Crafting - Home/Settlement", 
		"46": "Skills and Leveling", 
		"47": "Locations - Vanilla", 
		"48": "Player Settlement", 
		"49": "Clothing - Backpacks", 
		"5": "Armour", 
		"50": "Crafting - Other", 
		"51": "Immersion", 
		"52": "Pip-Boy", 
		"53": "Power Armour", 
		"55": "ReShade Presets", 
		"56": "Weather and Lighting", 
		"57": "Tattoos", 
		"58": "Character Presets", 
		"59": "Videos and Trailers", 
		"6": "Bug Fixes", 
		"61": "Transfer Settlement Blueprints", 
		"62": "VR", 
		"63": "Sim Settlements", 
		"7": "Buildings", 
		"8": "Cheats and God items", 
		"9": "Clothing"
	},
	"oblivion" : {
		"22": "New structures - Buildings", 
		"24": "Gameplay Effects and Changes", 
		"25": "Guilds/Factions", 
		"26": "Body, Face, and Hair", 
		"27": "Items and Objects - Player", 
		"28": "Miscellaneous", 
		"29": "Models And Textures", 
		"30": "New Lands", 
		"33": "NPC", 
		"34": "Races, Classes and Birthsigns", 
		"35": "Quests And Adventures", 
		"36": "Weapons And Armour", 
		"38": "Official Plugins", 
		"39": "Utilities", 
		"40": "Cheats and God Items", 
		"41": "Companions - CM Based", 
		"42": "User Interfaces", 
		"43": "Saved Games", 
		"45": "Videos and Trailers", 
		"51": "Animation", 
		"52": "Millionth Member Competition", 
		"53": "Cities, Towns, Villages and Hamlets", 
		"54": "Armour", 
		"55": "Weapons", 
		"58": "Landscape Changes", 
		"60": "Clothing", 
		"61": "Audio, Sound and Music", 
		"62": "Visuals and Graphics", 
		"65": "Companions - Creatures", 
		"66": "Companions - Other", 
		"67": "Player homes", 
		"68": "Castles, Palaces, Mansions and Estates", 
		"69": "Mercantiles (shops, stores, inns, taverns, etc)",
		"70": "Ruins, Forts and abandoned structures", 
		"73": "Skills and Leveling", 
		"74": "Environmental", 
		"75": "Magic - Spells &amp; Enchantments", 
		"76": "Stealth", 
		"77": "Combat", 
		"78": "Immersion", 
		"79": "Overhauls", 
		"82": "Modders Resources &amp; Tutorials", 
		"83": "Animals, Creatures, Mounts &amp; Horses", 
		"84": "Patches", 
		"85": "Items and Objects - World", 
		"88": "Dungeons - New", 
		"89": "Locations - New", 
		"90": "Locations - Vanilla", 
		"91": "Dungeons - Vanilla", 
		"92": "Collectables, Treasure Hunts and Puzzles", 
		"93": "Magic - Gameplay", 
		"94": "Magic - Alchemy", 
		"96": "Competition", 
		"97": "ENB Preset", 
		"98": "Books and Scrolls"
	},
	"newvegas" : {
		"100": "Bug Fixes", 
		"102": "Competition", 
		"103": "ENB presets", 
		"104": "Modders resources and tutorials", 
		"105": "Player Homes", 
		"106": "Weapons and Armour", 
		"107": "Ammo", 
		"108": "Crafting", 
		"109": "Overhauls", 
		"110": "Items - Food/Drinks/Chems/etc", 
		"111": "Patches", 
		"112": "Visuals and Graphics", 
		"113": "Creatures", 
		"114": "Perks", 
		"115": "Performance", 
		"116": "Collectibles", 
		"117": "Environment", 
		"118": "NPC - Vendors", 
		"119": "SweetFX Presets", 
		"120": "Vehicles", 
		"56": "Animation", 
		"58": "Cheats and God Items", 
		"59": "Utilities", 
		"60": "Videos and Trailers", 
		"61": "Saved Games/Characters", 
		"62": "Hair and Face Models", 
		"63": "User Interfaces", 
		"64": "Miscellaneous", 
		"66": "Models and Textures", 
		"67": "Clothing", 
		"68": "Weapons", 
		"69": "Armour", 
		"70": "Sounds and Music", 
		"71": "Gameplay Effects and Changes", 
		"72": "Buildings", 
		"73": "Companions", 
		"74": "Guilds/Factions", 
		"75": "New Lands and Locations", 
		"76": "NPC", 
		"77": "Quests and Adventures", 
		"88": "Radio stations", 
		"90": "Poses", 
		"99": "General"
	},
	"fallout3" : {
		"101": "Bug Fixes", 
		"102": "Modders Resources and Tutorials", 
		"103": "ENB Preset", 
		"104": "Environment", 
		"105": "Visuals and Graphics", 
		"106": "Overhauls", 
		"107": "Player Homes", 
		"108": "Collectibles", 
		"109": "ReShade Preset", 
		"110": "Vehicles", 
		"111": "NPC - Vendors", 
		"112": "Weapons and Armour", 
		"113": "Ammo", 
		"114": "Creatures", 
		"115": "Patches", 
		"116": "Performance", 
		"117": "Perks", 
		"56": "Animation", 
		"58": "Cheats and God Items", 
		"59": "Utilities", 
		"60": "Videos and Trailers", 
		"61": "Save Games", 
		"62": "Hair and Face Models", 
		"63": "User Interface", 
		"64": "Miscellaneous", 
		"66": "Models and Textures", 
		"67": "Clothing", 
		"68": "Weapons", 
		"69": "Armour", 
		"70": "Sounds and Music", 
		"71": "Gameplay Effects and Changes", 
		"72": "Buildings", 
		"73": "Companions", 
		"74": "Guilds/Factions", 
		"75": "New Lands and Locations", 
		"76": "NPC", 
		"77": "Quests and Adventures", 
		"78": "Official", 
		"79": "Millionth Member Competition", 
		"88": "Radio stations", 
		"90": "Poses"
	},
	"morrowind" : {
		"10": "New Lands", 
		"11": "NPCs", 
		"12": "Official Plugins", 
		"13": "Quests and Adventures", 
		"14": "Races, Classes, and Birthsigns", 
		"15": "Utilities", 
		"16": "Weapons and Armour", 
		"17": "Modders Resources and Tutorials", 
		"18": "Bug Fixes", 
		"19": "Creatures", 
		"2": "Buildings", 
		"20": "Books and Scrolls", 
		"21": "Animations", 
		"22": "Cheats and God items", 
		"23": "Companions", 
		"24": "User Interface", 
		"25": "Audio - Music", 
		"26": "ENB Preset", 
		"27": "Player homes", 
		"28": "Patches", 
		"29": "Overhauls", 
		"3": "Dungeons and Locations", 
		"30": "Splash Screens", 
		"31": "Weapons", 
		"32": "Audio - SFX and Voices", 
		"33": "Magic", 
		"34": "Towns and Villages", 
		"35": "Skills and Attributes", 
		"36": "Immersion", 
		"37": "Armour - Shields", 
		"38": "Armour", 
		"4": "Gameplay Effects and Changes", 
		"5": "Guilds/Factions", 
		"6": "Body, Face, and Hair", 
		"7": "Items, Objects, and Clothes", 
		"8": "Miscellaneous", 
		"9": "Models and Textures"
	},
	"stardewvalley" : {
		"10": "User Interface", 
		"11": "Cheats", 
		"12": "Audio", 
		"13": "Clothing", 
		"14": "Crops", 
		"15": "Items", 
		"16": "Locations", 
		"17": "Buildings", 
		"18": "Events", 
		"19": "Interiors", 
		"2": "Miscellaneous", 
		"20": "Dialogue", 
		"21": "Maps", 
		"22": "Crafting", 
		"23": "Furniture", 
		"25": "Visuals and Graphics", 
		"26": "Fishing", 
		"3": "Gameplay Mechanics", 
		"4": "Player", 
		"5": "Characters", 
		"6": "Portraits", 
		"7": "Livestock &amp; Animals", 
		"8": "Pets / Horses", 
		"9": "Modding Tools"
	},
	"witcher3" : {
		"10": "Armour", 
		"11": "Cheats and God items", 
		"12": "Bug Fixes", 
		"13": "Combat", 
		"14": "Gwent", 
		"15": "Modders Resources and Tutorials", 
		"16": "ReShade Preset", 
		"17": "Gameplay Changes", 
		"18": "Models and Textures", 
		"19": "Weapons", 
		"2": "Miscellaneous", 
		"20": "Signs", 
		"21": "Save Games", 
		"22": "Overhaul", 
		"23": "Characters", 
		"24": "Items", 
		"25": "Camera", 
		"27": "Debug Console", 
		"28": "Alchemy and Crafting", 
		"29": "Weapons and Armour", 
		"3": "Controller Button Layout", 
		"30": "Inventory", 
		"31": "Balancing", 
		"32": "Immersion", 
		"33": "Utilities", 
		"35": "Audio - Music", 
		"36": "Audio - Voice", 
		"37": "Audio - SFX", 
		"4": "Visuals and Graphics", 
		"40": "Performance", 
		"41": "Hair and Face", 
		"42": "Quests and Adventures", 
		"5": "Skills and Leveling", 
		"6": "User Interface", 
		"8": "Tweaks"
	},
	"monsterhunterworld" : {
		"10": "Weapons", 
		"11": "Audio &amp; Music", 
		"12": "Environmental", 
		"13": "Monsters", 
		"2": "Miscellaneous", 
		"3": "User Interface", 
		"4": "Graphics &amp; Visuals", 
		"5": "Tools &amp; Utilities", 
		"6": "ReShade Presets", 
		"7": "Armour and Clothing", 
		"8": "Characters", 
		"9": "Quests and Adventures"
	},
	"dragonage" : {
		"10": "Companions", 
		"11": "Locations: Dungeons", 
		"13": "Gameplay Effects and Changes", 
		"14": "Face and Hair", 
		"15": "Items", 
		"18": "Locations", 
		"19": "Crafting", 
		"21": "Locations: Stores and Taverns", 
		"22": "Miscellaneous", 
		"23": "Models and Textures", 
		"26": "NPCs", 
		"27": "Quests and Adventures", 
		"29": "Saved Games", 
		"3": "Creatures", 
		"30": "Combat, Skills, Magic, and Leveling", 
		"32": "User Interface", 
		"33": "Utilities", 
		"34": "Videos and Trailers", 
		"35": "Visuals and Graphics", 
		"36": "Weapons", 
		"37": "Weapons and Armour", 
		"39": "Modders Resources and Tutorials", 
		"4": "Animation", 
		"40": "Overhauls", 
		"43": "Bug Fixes", 
		"44": "ReShade Preset", 
		"5": "Armour", 
		"6": "Audio", 
		"7": "Cheats and God Items", 
		"9": "Clothing"
	},
	"starwarsbattlefront22017" : {
		"1": "Vehicles", 
		"10": "Utilities", 
		"11": "Weapons", 
		"14": "Hero Skins and Abilities", 
		"15": "Class Skins and Abilities", 
		"2": "Miscellaneous", 
		"3": "Audio", 
		"4": "Maps", 
		"5": "Visuals and Graphics", 
		"6": "Models and Textures", 
		"7": "Gameplay Effects and Changes", 
		"8": "User Interface"
	},
	"dragonageinquisition" : {
		"10": "Weapons", 
		"11": "Armour", 
		"12": "Clothing", 
		"13": "Audio", 
		"14": "Cheats and God Items", 
		"16": "Combat, Skills, Magic, and Leveling", 
		"17": "Creatures", 
		"2": "Saved Games", 
		"21": "Bug Fixes", 
		"22": "User Interface", 
		"23": "Visuals and Graphics", 
		"24": "Character Creation", 
		"26": "Face and Hair", 
		"27": "Modders Resources and Tutorials", 
		"29": "ReShade preset", 
		"3": "Utilities", 
		"30": "NPCs", 
		"31": "Crafting", 
		"32": "Gameplay Effects and Changes", 
		"33": "Tattoos", 
		"35": "Sliders", 
		"4": "Overhauls", 
		"5": "Miscellaneous", 
		"6": "Companions", 
		"7": "Animation", 
		"8": "Models and Textures", 
		"9": "Videos and Trailers"
	},
	"mountandblade" : {
		"12": "Modules", 
		"20": "Models and Textures", 
		"31": "Items, Graphics and Sound", 
		"32": "Item Packs", 
		"34": "Utilities", 
		"35": "Miscellaneous", 
		"36": "Modders Resources and Tutorials", 
		"39": "Gameplay Mechanics", 
		"40": "Scenes and Maps", 
		"42": "Audio", 
		"43": "Visuals and Graphics"
	},
	"bladeandsorcery" : {
		"10": "Audio", 
		"12": "Waves", 
		"13": "Maps", 
		"14": "Armour", 
		"2": "Miscellaneous", 
		"4": "Spells", 
		"5": "Enemies", 
		"7": "Gameplay Effects and Changes", 
		"8": "Weapons", 
		"9": "Apparel"
	},
	"mountandblade2bannerlord" : {
		"14": "Modders Resources and Tutorials", 
		"15": "User Interface", 
		"16": "Characters", 
		"17": "Troops and Units", 
		"18": "Armour and Clothing", 
		"19": "Weapons and Shields", 
		"2": "Miscellaneous", 
		"20": "Saved Games", 
		"21": "Character Presets", 
		"22": "Banner Presets", 
		"23": "Total Conversion", 
		"24": "Total Overhaul", 
		"3": "Audio", 
		"4": "Visuals and Graphics", 
		"6": "Utilities", 
		"7": "Scenes and Maps", 
		"8": "Gameplay Effects and Changes"
	},
	"darksouls" : {
		"102": "Miscellaneous", 
		"110": "Weapons", 
		"111": "Armour", 
		"112": "Weapons and Armour", 
		"113": "Shields", 
		"114": "User Interface", 
		"115": "Visuals and Graphics", 
		"117": "Creatures", 
		"122": "Audio - Music", 
		"123": "Models and Textures", 
		"124": "Audio - SFX", 
		"125": "ReShade Preset", 
		"126": "Gameplay Changes", 
		"127": "Body Textures", 
		"128": "Clothing", 
		"129": "Save Games", 
		"99": "Utilities"
	},
	"dragonage2" : {
		"41": "Crafting", 
		"42": "Creatures", 
		"43": "Animation", 
		"44": "Armour", 
		"45": "Audio", 
		"46": "Cheats and God Items", 
		"48": "Clothing", 
		"49": "Companions", 
		"52": "Gameplay Effects and Changes", 
		"53": "Face and Hair", 
		"54": "Items", 
		"56": "Locations", 
		"58": "Miscellaneous", 
		"59": "Models and Textures", 
		"62": "NPCs", 
		"65": "Saved Games", 
		"67": "Combat, Skills, Magic, and Leveling", 
		"69": "User Interface", 
		"70": "Utilities", 
		"71": "Videos and Trailers", 
		"72": "Visuals and Graphics", 
		"73": "Weapons", 
		"74": "Weapons and Armour", 
		"75": "Bug Fixes", 
		"76": "Modders Resources and Tutorials", 
		"77": "ReShade Preset"
	},
	"mbwarband" : {
		"28": "Modules", 
		"30": "Models and Textures", 
		"39": "Scenes and Maps", 
		"43": "Utilities", 
		"47": "Visuals and Graphics", 
		"53": "Miscellaneous", 
		"54": "Modders Resources and Tutorials", 
		"55": "Audio", 
		"56": "User Interface", 
		"57": "Banners"
	},
	"nomanssky" : {
		"10": "Audio", 
		"11": "Cheats", 
		"12": "Overhauls", 
		"13": "Ships", 
		"14": "Scripts", 
		"15": "Textures", 
		"16": "Tweaks &amp; Fixes", 
		"17": "Weapons", 
		"19": "Vehicles", 
		"2": "Miscellaneous", 
		"20": "Buildings", 
		"3": "ReShade Presets", 
		"4": "User Interface", 
		"5": "Utilities", 
		"6": "Environment", 
		"7": "Gameplay", 
		"8": "Creatures", 
		"9": "Visuals and Graphics"
	},
	"warthunder" : {
		"10": "Modder resources", 
		"12": "Tank Skins", 
		"2": "Miscellaneous", 
		"3": "Plane Skins", 
		"9": "Utilities"
	},
	"kingdomcomedeliverance" : {
		"10": "Player and Inventory", 
		"11": "Saved Games", 
		"12": "Texture Replacement", 
		"13": "User Interface", 
		"14": "Utilities and Tools", 
		"15": "Weapons", 
		"16": "Armour", 
		"2": "Miscellaneous", 
		"3": "AI and NPC", 
		"4": "Audio", 
		"5": "Cheats", 
		"6": "Gameplay", 
		"7": "Graphics and Visuals", 
		"8": "Model Replacement", 
		"9": "Performance"
	},
	"darkestdungeon" : {
		"10": "Dialogue", 
		"11": "Immersion", 
		"12": "Skins", 
		"13": "Colour Schemes", 
		"14": "Visuals and Graphics", 
		"15": "Balancing", 
		"16": "Items", 
		"17": "Classes: Modified", 
		"18": "Monsters and Creatures", 
		"19": "Gameplay Changes", 
		"2": "Miscellaneous", 
		"3": "Bug Fixes", 
		"4": "Classes: New", 
		"5": "Combat", 
		"6": "Modders resources and tutorials", 
		"7": "Overhaul", 
		"8": "User Interface", 
		"9": "Difficulty"
	},
	"7daystodie" : {
		"11": "Crafting", 
		"12": "Zombies", 
		"13": "Vehicles", 
		"14": "Cheats", 
		"15": "Visuals and Graphics", 
		"16": "Quests", 
		"17": "Weapons", 
		"18": "Items - Food", 
		"19": "Animals and Creatures", 
		"2": "Miscellaneous", 
		"20": "Audio", 
		"3": "XML Edits", 
		"4": "User Interface", 
		"5": "Overhauls", 
		"6": "Gameplay Effects and Changes", 
		"7": "Prefabs", 
		"8": "Items and Loot", 
		"9": "Utilities and Modders Resources"
	},
	"metalgearsolidvtpp" : {
		"10": "Utilities", 
		"11": "Playable Characters", 
		"12": "Modders Resources and Tutorials", 
		"13": "ReShade Preset", 
		"14": "Audio", 
		"15": "Abilities", 
		"16": "Camera", 
		"2": "Miscellaneous", 
		"3": "Visuals and Graphics", 
		"4": "Models and Textures", 
		"5": "Gameplay Effects and Changes", 
		"6": "User Interface", 
		"7": "Weapons", 
		"8": "Cheats", 
		"9": "Saved Games"
	},
	"darksouls2" : {
		"10": "Body Textures", 
		"11": "Visuals and Graphics", 
		"12": "Audio - SFX", 
		"14": "Creatures", 
		"15": "Clothing", 
		"16": "Gameplay Changes", 
		"17": "Weapons and Armour", 
		"18": "Audio - Music", 
		"19": "ReShade Preset", 
		"2": "Miscellaneous", 
		"20": "ENB Preset", 
		"3": "Armour", 
		"4": "Models and Textures", 
		"5": "Shields", 
		"6": "Weapons", 
		"7": "User Interface", 
		"8": "Utilities", 
		"9": "Save Games"
	},
	"starbound" : {
		"10": "User Interface", 
		"11": "Visuals and Graphics", 
		"12": "Worlds and Builds", 
		"13": "Procedurally Generated Structures", 
		"14": "Custom Ships", 
		"15": "Utilities", 
		"16": "Audio - SFX, Music, and Voice", 
		"17": "Crafting", 
		"18": "Biomes and Subbiomes", 
		"19": "Modders Resources", 
		"2": "Miscellaneous", 
		"20": "Playable Race", 
		"21": "Replacements", 
		"22": "New Items/Objects", 
		"23": "Player model", 
		"24": "Weapons and Armour", 
		"25": "Cheats", 
		"26": "Clothing", 
		"27": "Armour", 
		"28": "Overhauls", 
		"3": "Weapons", 
		"4": "Tools and Equipment", 
		"6": "Materials and Placeables", 
		"7": "NPCs and Creatures", 
		"8": "Gameplay Effects and Changes", 
		"9": "Texture Replacements"
	},
	"worldoftanks" : {
		"100": "Skins - Tanks", 
		"101": "Skins - Crew", 
		"102": "Miscellaneous", 
		"103": "Skins - Other", 
		"105": "UI - Crosshairs", 
		"106": "UI - Other", 
		"107": "Icons", 
		"108": "Hangars", 
		"109": "Flags", 
		"110": "Audio - Music", 
		"111": "Visuals and Graphics", 
		"112": "Audio - Voice", 
		"98": "Audio - Sounds", 
		"99": "Utilities"
	},
	"acecombat7skiesunknown" : {
		"2": "Miscellaneous", 
		"3": "Models and Textures", 
		"4": "User Interface"
	},
	"masseffectandromeda" : {
		"11": "Companions", 
		"12": "Crafting", 
		"13": "Creatures", 
		"14": "Face and Hair", 
		"15": "Gameplay Effects and Changes", 
		"17": "Modders Resources and Tutorials", 
		"19": "Models and Textures", 
		"2": "Miscellaneous", 
		"20": "NPCs", 
		"21": "Overhauls", 
		"22": "Multiplayer", 
		"3": "Animation", 
		"4": "Armour", 
		"5": "Audio", 
		"6": "Bug Fixes", 
		"7": "Character Creation", 
		"8": "Cheats and God Items", 
		"9": "Clothing"
	},
	"xcom2" : {
		"10": "Weapons", 
		"11": "Armour", 
		"12": "Classes", 
		"13": "Enemies", 
		"14": "Animation", 
		"15": "Audio - Voice", 
		"16": "Tattoos", 
		"17": "Visuals and Graphics", 
		"2": "Miscellaneous", 
		"3": "Character Pool", 
		"4": "Gameplay tweaks", 
		"5": "Nationality", 
		"6": "Cheats", 
		"7": "User Interface", 
		"8": "Soldier mods", 
		"9": "ReShade Preset"
	},
	"devilmaycry5" : {
		"10": "User Interface", 
		"2": "Miscellaneous", 
		"3": "Models and Textures", 
		"4": "ReShade Presets", 
		"5": "Audio and SFX", 
		"6": "Costumes", 
		"7": "Weapons and items", 
		"8": "Cheats", 
		"9": "Tools and Utilities"
	},
	"masseffect3" : {
		"11": "Audio - Music", 
		"12": "Body, Face, and Hair", 
		"13": "Armour", 
		"14": "Audio - SFX", 
		"15": "ReShade Preset", 
		"16": "Saved Games", 
		"17": "Models and Textures", 
		"18": "Modders Resources and Tutorials", 
		"2": "Miscellaneous", 
		"3": "Models", 
		"4": "Story", 
		"5": "Textures", 
		"6": "Utilities", 
		"7": "Clothing", 
		"8": "Videos and Trailers", 
		"9": "Gameplay Effects and Changes"
	},
	"kenshi" : {
		"13": "Buildings", 
		"14": "Gameplay Effects and Changes", 
		"15": "Factions", 
		"16": "Mercenaries/Recruits", 
		"17": "Game Starts", 
		"18": "Races", 
		"19": "Weapons and Armour", 
		"2": "Miscellaneous", 
		"20": "Bug Fixes", 
		"21": "Total Overhaul", 
		"3": "Weapons", 
		"4": "Visuals and Graphics", 
		"5": "Models and Textures", 
		"9": "Armour"
	},
	"fallout76" : {
		"10": "Radio", 
		"11": "Gameplay Effects and Changes", 
		"12": "Audio - SFX", 
		"13": "Body, Face, and Hair", 
		"14": "Pip-Boy", 
		"15": "Weapons", 
		"16": "Performance", 
		"17": "Bug Fixes", 
		"18": "Environment", 
		"19": "Audio - Music", 
		"2": "Miscellaneous", 
		"20": "Audio - Voice", 
		"3": "ENB and ReShade", 
		"4": "Models and Textures", 
		"5": "User Interface", 
		"6": "Tools and Utilities", 
		"8": "Animations", 
		"9": "Patches"
	},
	"darksouls3" : {
		"10": "Utilities", 
		"11": "Body Textures", 
		"12": "Clothing", 
		"13": "Armour", 
		"14": "Weapons and Armour", 
		"15": "Weapons", 
		"16": "Shields", 
		"17": "User Interface", 
		"18": "Creatures", 
		"2": "Miscellaneous", 
		"3": "Save Games", 
		"4": "ReShade Preset", 
		"5": "Visuals and Graphics", 
		"6": "Audio - SFX", 
		"7": "Audio - Music", 
		"8": "Models and Textures", 
		"9": "Gameplay Changes"
	},
	"sekiro" : {
		"11": "Sound", 
		"12": "Gameplay Effects and Changes", 
		"13": "Customisation", 
		"14": "Save Games", 
		"2": "Miscellaneous", 
		"3": "ReShade Presets", 
		"4": "Death Screens", 
		"5": "Utilities", 
		"6": "Weapons and Armour", 
		"9": "User Interface"
	},
	"witcher2" : {
		"10": "Weapons", 
		"11": "Armour", 
		"12": "Weapons and Armour", 
		"13": "Bug Fixes", 
		"14": "Utilities", 
		"15": "Cheats and God Items", 
		"2": "Abilities", 
		"3": "Alchemy and Crafting", 
		"33": "Gameplay Changes", 
		"34": "Save Games", 
		"35": "Audio - SFX", 
		"36": "Audio - Music", 
		"39": "Visuals and Graphics", 
		"4": "Inventory", 
		"40": "Hair", 
		"41": "ENB Preset", 
		"42": "Characters", 
		"44": "Performance", 
		"45": "ReShade Preset", 
		"5": "Quests And Adventures", 
		"6": "Items", 
		"7": "Models and Textures", 
		"8": "User Interfaces", 
		"9": "Miscellaneous"
	},
	"neverwinter2" : {
		"10": "Miscellaneous", 
		"11": "Plug-ins", 
		"12": "Portraits", 
		"13": "Prefabs - Areas", 
		"14": "Prefabs - Blueprints", 
		"15": "PWC Files", 
		"16": "Scripts", 
		"17": "Visuals and Graphics", 
		"18": "Sounds", 
		"19": "Textures", 
		"20": "Utilities", 
		"21": "User Interface", 
		"22": "Tutorials", 
		"23": "Animations", 
		"24": "Creatures", 
		"25": "Persistent Worlds", 
		"3": "Characters", 
		"4": "Hakpaks - Original", 
		"5": "Hakpaks - Combined", 
		"6": "Hakpaks - For Modules", 
		"7": "Models", 
		"8": "Modules", 
		"9": "Videos and trailers"
	},
	"x4foundations" : {
		"10": "Weapons", 
		"11": "Galaxy", 
		"12": "Modding Resource", 
		"13": "Tools and Utilities", 
		"14": "Traders", 
		"15": "Stations", 
		"2": "Miscellaneous", 
		"3": "Gameplay Effects and Changes", 
		"4": "Audio", 
		"5": "Graphics and Visuals", 
		"6": "Ship mods", 
		"7": "User Interface", 
		"8": "Cheats", 
		"9": "Characters"
	},
	"residentevil22019" : {
		"2": "Miscellaneous", 
		"3": "Models and Textures", 
		"4": "Reshade Presets", 
		"6": "Audio and SFX", 
		"7": "Weapons and Items", 
		"8": "Tools and Utilities"
	},
	"dragonsdogma" : {
		"11": "Armour", 
		"12": "Weapons", 
		"13": "ENB Preset", 
		"14": "Skills and Augments", 
		"15": "Tweaks", 
		"16": "Utilities", 
		"17": "Visuals and Graphics", 
		"18": "Audio - Voice", 
		"19": "Audio - Music", 
		"2": "Miscellaneous", 
		"20": "Creatures", 
		"21": "Modders Resources and Tutorials", 
		"3": "Models and Textures", 
		"4": "Audio - Misc", 
		"5": "Game Mechanics", 
		"6": "User Interface", 
		"8": "Cheats"
	},
	"battletech" : {
		"10": "Mechs and Vehicles", 
		"11": "Modders Resources and Tutorials", 
		"12": "Campaign", 
		"2": "Miscellaneous", 
		"3": "Cheats", 
		"4": "Balance", 
		"6": "Gameplay Alterations", 
		"7": "Tools and Utilities", 
		"8": "User Interface", 
		"9": "Equipment"
	},
	"jurassicworldevolution" : {
		"2": "Miscellaneous", 
		"3": "Trees and Foliage", 
		"4": "Dinosaurs"
	},
	"halothemasterchiefcollection" : {
		"10": "Forge", 
		"11": "Menu and UI", 
		"12": "Vehicles", 
		"13": "Visual Presets", 
		"14": "Modder's Resources",
		"15": "Graphics", 
		"2": "Miscellaneous", 
		"3": "Utilities", 
		"4": "Gametypes", 
		"5": "Maps", 
		"6": "Weapons", 
		"7": "Firefight", 
		"8": "Campaign", 
		"9": "Audio"
	},
	"xcom" : {
		"10": "Saved Games", 
		"11": "Bug Fixes", 
		"12": "Textures", 
		"13": "Graphic Enhancement", 
		"14": "Realism", 
		"15": "Total Overhaul", 
		"16": "Audio - Voice", 
		"2": "Tools and Utilities", 
		"3": "User Interface", 
		"4": "Weapons", 
		"5": "Miscellaneous", 
		"6": "Armour", 
		"7": "Gameplay Effects", 
		"8": "Audio - SFX and Music", 
		"9": "Cheats"
	},
	"subnautica" : {
		"10": "Gameplay Effects and Changes", 
		"11": "Library", 
		"12": "Environment", 
		"13": "Adventure", 
		"15": "Crafting", 
		"16": "Vehicles and Upgrades", 
		"17": "Multiplayer", 
		"2": "Miscellaneous", 
		"3": "Shader Presets", 
		"4": "Utilities", 
		"5": "User Interface", 
		"7": "Save Games", 
		"8": "Buildables", 
		"9": "Items"
	},
	"divinityoriginalsin2" : {
		"10": "Crafting", 
		"11": "Creatures", 
		"12": "Gameplay", 
		"13": "Hair/Faces", 
		"14": "Music", 
		"15": "Quests and Adventures", 
		"16": "Skills", 
		"17": "UI", 
		"18": "Cheats", 
		"19": "Add-On", 
		"2": "Miscellaneous", 
		"20": "Bug Fixes / Patches", 
		"21": "Weapons", 
		"22": "Quality of Life Improvements", 
		"23": "Class", 
		"24": "Utility", 
		"25": "Official Patches", 
		"26": "Items", 
		"3": "Models and Textures", 
		"4": "Overhauls", 
		"5": "Armor", 
		"6": "Audio", 
		"7": "Campaigns", 
		"8": "Clothing", 
		"9": "Companions"
	},
	"codevein" : {
		"2": "Miscellaneous", 
		"3": "Visuals and Graphics", 
		"4": "Armour and Clothing", 
		"5": "Weapons", 
		"6": "Audio", 
		"7": "Tools and Utilities", 
		"8": "Body, Face and Hair"
	},
	"finalfantasy14" : {
		"2": "Miscellaneous", 
		"3": "ReShade Preset"
	},
	"pillarsofeternity2" : {
		"10": "Audio", 
		"11": "Companions", 
		"12": "Appearance &amp; Visuals", 
		"13": "ENB &amp; ReShade Presets", 
		"14": "Races", 
		"15": "Translations", 
		"16": "Utilities", 
		"17": "User Interface", 
		"18": "Classes", 
		"2": "Miscellaneous", 
		"3": "Abilities, Skills, and Spells", 
		"4": "Gameplay", 
		"5": "Portraits", 
		"6": "Tweaks", 
		"7": "Items", 
		"8": "Cheats", 
		"9": "Weapons"
	},
	"stateofdecay" : {
		"10": "Cheats", 
		"11": "Realism", 
		"12": "Skins", 
		"13": "Gameplay", 
		"14": "Vehicles", 
		"15": "Visuals and Graphics", 
		"16": "Characters", 
		"17": "Models and Textures", 
		"18": "Audio", 
		"19": "Overhauls", 
		"2": "Miscellaneous", 
		"20": "Animations", 
		"3": "Bug fixes", 
		"4": "Character Replacement", 
		"5": "User Interface", 
		"6": "Tools", 
		"7": "AI", 
		"8": "Weapon Mods", 
		"9": "Buildings/Bases/Environment"
	},
	"kotor" : {
		"10": "Weapons - Lightsabers", 
		"11": "Weapons - Blasters", 
		"13": "Bug Fixes", 
		"14": "Content - New", 
		"15": "Content - Restored", 
		"17": "Launchers", 
		"19": "Character Models", 
		"2": "Miscellaneous", 
		"28": "Character Progression", 
		"29": "Characters", 
		"3": "Armour and Clothing", 
		"31": "Feats and Powers", 
		"32": "User Interface", 
		"33": "Character Heads", 
		"34": "Items", 
		"35": "Merchants", 
		"36": "Content - Modified", 
		"38": "Party Members", 
		"39": "Recruitment Mods", 
		"4": "Models and Textures", 
		"42": "Scripts", 
		"47": "Character Textures", 
		"5": "Utilities", 
		"50": "Modules", 
		"51": "Audio - Music", 
		"6": "Weapons - Misc", 
		"7": "Visuals and Graphics", 
		"8": "Audio", 
		"9": "Companions"
	},
	"grimrock" : {
		"111": "Audio", 
		"112": "Utilities", 
		"113": "Models and Textures", 
		"114": "Weapons", 
		"115": "Armour", 
		"116": "Potions", 
		"117": "Monsters", 
		"118": "Dungeons", 
		"119": "Miscellaneous", 
		"120": "Portraits"
	},
	"thesims4" : {
		"2": "Miscellaneous", 
		"3": "Clothing", 
		"4": "Gameplay", 
		"5": "Decorations"
	},
	"dyinglight" : {
		"10": "Performance", 
		"11": "Save Games", 
		"12": "Skills", 
		"13": "Outfits", 
		"14": "Weapons", 
		"15": "AI", 
		"16": "Crafting", 
		"17": "Items and Loot", 
		"18": "User Interface", 
		"19": "Environment", 
		"2": "Miscellaneous", 
		"20": "Patches", 
		"3": "Gameplay Effects and Changes", 
		"4": "Cheats", 
		"5": "Modders Resources and Tutorials", 
		"6": "Immersion", 
		"7": "Visuals and Graphics", 
		"8": "Sound and Music", 
		"9": "Overhauls"
	},
	"starwarsbattlefront2015" : {
		"10": "User Interface", 
		"11": "Cheats", 
		"12": "Graphics and Effects", 
		"13": "Overhauls", 
		"14": "Weapons", 
		"15": "Vehicles", 
		"16": "Converions", 
		"2": "Miscellaneous", 
		"3": "Models and Textures", 
		"4": "Game Modes", 
		"5": "Gameplay Effects and Changes", 
		"6": "Audio", 
		"7": "Bug Fixes", 
		"8": "Modders Resources and Tutorials", 
		"9": "ReShade Presets"
	},
	"tabletopsimulator" : {
		"2": "Miscellaneous", 
		"3": "Card Games", 
		"4": "Board Games", 
		"5": "Player Pieces", 
		"6": "User Interface", 
		"7": "Utilities", 
		"8": "Dice Games", 
		"9": "Tabletop Games"
	},
	"rimworld" : {
		"10": "Audio", 
		"11": "Models and Textures", 
		"12": "User Interface", 
		"13": "Utilities", 
		"14": "Music", 
		"15": "Items - Food", 
		"16": "Items - Drugs and Alcohol", 
		"17": "Items - Miscellaneous", 
		"18": "Animals", 
		"19": "Power", 
		"2": "Miscellaneous", 
		"20": "Security", 
		"21": "Temperature", 
		"22": "Armour and Clothing", 
		"23": "Custom Traders", 
		"24": "Mod Packs", 
		"25": "Storyteller", 
		"26": "Custom Factions", 
		"3": "Cheats", 
		"4": "Overhauls", 
		"5": "Visuals and Graphics", 
		"6": "Weapons", 
		"7": "Production", 
		"8": "Custom Enemies", 
		"9": "Custom Events"
	},
	"xrebirth" : {
		"11": "User Interface", 
		"12": "Miscellaneous", 
		"15": "Gameplay", 
		"16": "Cheats", 
		"19": "Animation", 
		"22": "Audio", 
		"26": "Bug Fixes", 
		"29": "Environmental Changes", 
		"32": "Models and Textures", 
		"35": "Visuals and Graphics", 
		"37": "Saved Games", 
		"38": "Characters", 
		"39": "Weapons", 
		"40": "Artificial Intelligence", 
		"41": "Combat", 
		"7": "Utilities"
	},
	"witcher" : {
		"17": "Abilities", 
		"18": "Alchemy and Crafting", 
		"19": "Armour", 
		"20": "Bug Fixes", 
		"21": "Cheats and God Items", 
		"22": "Inventory", 
		"23": "Items", 
		"24": "Miscellaneous", 
		"25": "Quests And Adventures", 
		"26": "Models and Textures", 
		"27": "User Interfaces", 
		"28": "Utilities", 
		"29": "Weapons", 
		"30": "Weapons and Armour", 
		"31": "Gameplay Changes", 
		"32": "Visuals and Graphics", 
		"33": "Save Games", 
		"35": "Audio - Music", 
		"36": "Audio - SFX", 
		"37": "ReShade Preset", 
		"38": "Characters", 
		"39": "ENB Preset", 
		"40": "Camera"
	},
	"divinityoriginalsin2definitiveedition" : {
		"10": "Overhaul", 
		"11": "Gameplay / Balance Changes", 
		"12": "Armors", 
		"13": "Character Creation", 
		"14": "Items", 
		"15": "Add-On", 
		"16": "Audio", 
		"17": "Bug Fixes / Patches", 
		"18": "Models and Textures", 
		"19": "Weapons", 
		"2": "Miscellaneous", 
		"20": "Classes", 
		"3": "Quality of Life Improvements", 
		"4": "Cheats", 
		"5": "UI", 
		"6": "Utility", 
		"7": "Skills", 
		"8": "Talents", 
		"9": "Runes"
	},
	"masseffect2" : {
		"10": "Saved Games", 
		"11": "Tutorials / Guides", 
		"2": "Miscellaneous", 
		"3": "Coalesced / INI", 
		"4": "Gameplay Effects and Changes", 
		"5": "Textures", 
		"6": "User Interface", 
		"7": "Utilities", 
		"8": "Resources", 
		"9": "Shader Presets"
	},
	"darksoulsremastered" : {
		"2": "Miscellaneous", 
		"3": "User Interface", 
		"4": "Models and Textures", 
		"5": "Reshade Preset", 
		"6": "Audio", 
		"7": "Weapons, Armour &amp; Clothing", 
		"8": "Utilities", 
		"9": "Gameplay"
	},
	"kotor2" : {
		"10": "Weapons - Misc", 
		"11": "Modders Resources and Tutorials", 
		"12": "Immersion", 
		"13": "Utilities", 
		"14": "Content - New", 
		"15": "Content - Restored", 
		"16": "Feats and Powers", 
		"18": "Audio", 
		"2": "Miscellaneous", 
		"20": "Launchers", 
		"22": "Character Models", 
		"32": "Character Progression", 
		"33": "Characters", 
		"36": "User Interface", 
		"37": "Character Heads", 
		"38": "Items", 
		"4": "Gameplay Effects and Changes", 
		"40": "Merchants", 
		"41": "Content - Modified", 
		"42": "Modules", 
		"43": "Party Members", 
		"44": "Recruitment Mods", 
		"47": "Scripts", 
		"5": "Models and Textures", 
		"52": "Character Textures", 
		"54": "Ebon Hawk Skins", 
		"55": "ReShade Preset", 
		"56": "Visuals and Graphics", 
		"6": "Cheats", 
		"7": "Armour and Clothing", 
		"8": "Weapons - Blasters", 
		"9": "Weapons - Lightsabers"
	},
	"residentevil32020" : {
		"2": "Miscellaneous", 
		"3": "Visuals and Graphics", 
		"4": "Models and Textures", 
		"5": "Audio and SFX", 
		"6": "Tools and Utilities", 
		"7": "User Interface", 
		"8": "Weapons and Items"
	},
	"borderlands2" : {
		"10": "User Interface", 
		"11": "Utilities", 
		"12": "Overhauls", 
		"13": "ReShade/SweetFX Presets", 
		"14": "Weapons", 
		"15": "Vault Hunters", 
		"16": "Gameplay Changes", 
		"17": "Cheats and God items", 
		"18": "Gear", 
		"19": "Mod Packs", 
		"2": "Miscellaneous", 
		"20": "Performance", 
		"21": "Modders Resources and Tutorials", 
		"22": "Audio - Voice", 
		"3": "Save Games", 
		"4": "Models and Textures", 
		"5": "Graphics and Visuals", 
		"6": "Bug Fixes", 
		"7": "Maps", 
		"8": "Audio - Music", 
		"9": "Audio - SFX"
	},
	"mysummercar" : {
		"10": "Visuals and Graphics", 
		"11": "Audio", 
		"2": "Miscellaneous", 
		"3": "Game Mechanics", 
		"4": "Items", 
		"5": "Vehicle Parts", 
		"6": "Vehicles", 
		"8": "Utilities", 
		"9": "Saved Games"
	},
	"reddeadredemption2" : {
		"10": "Save Games", 
		"11": "User Interface", 
		"12": "Utilities", 
		"13": "Tools", 
		"14": "Transport", 
		"15": "Weapons", 
		"16": "Scripts", 
		"17": "Player", 
		"18": "Maps", 
		"4": "Miscellaneous", 
		"5": "ReShade Presets", 
		"6": "Gameplay Effects and Changes", 
		"7": "Models and Textures", 
		"8": "Audio", 
		"9": "Cheats and God items"
	},
	"gta5" : {
		"10": "Models and Textures", 
		"11": "Gameplay Effects and Changes", 
		"12": "Maps", 
		"13": "Cops", 
		"14": "Tweaks", 
		"2": "Miscellaneous", 
		"3": "Scripts", 
		"4": "Weapons", 
		"5": "Vehicles", 
		"6": "Visuals and Graphics", 
		"7": "Utilities", 
		"8": "Sound and music", 
		"9": "ReShade Preset"
	},
	"ahatintime" : {
		"10": "Remixes", 
		"11": "Quality of Life", 
		"12": "Stickers", 
		"2": "Miscellaneous", 
		"3": "Maps and Levels", 
		"4": "Hats and Costumes", 
		"5": "Dyes", 
		"6": "Badges", 
		"7": "Weapons", 
		"8": "Asset Replacement", 
		"9": "Animation"
	},
	"narutorevolution" : {
		"2": "Miscellaneous", 
		"3": "Movesets", 
		"4": "User Interface", 
		"5": "Textures"
	},
	"mechwarrior5mercenaries" : {
		"2": "Miscellaneous", 
		"3": "Visuals and Graphics", 
		"4": "Cheats", 
		"5": "Audio", 
		"6": "Gameplay Effects and Changes"
	},
	"battlebrothers" : {
		"2": "Miscellaneous"
	},
	"starwarsjedifallenorder" : {
		"10": "Models and Textures", 
		"2": "Miscellaneous", 
		"3": "Visuals and Graphics", 
		"4": "Utilities", 
		"5": "User Interface", 
		"6": "Gameplay Effects and Changes", 
		"7": "Outfits", 
		"8": "Weapons", 
		"9": "Audio"
	},
	"pillarsofeternity" : {
		"10": "Audio - Music", 
		"11": "Bugfixes", 
		"12": "Gameplay", 
		"13": "Abilities, Skills, and Spells", 
		"14": "Audio - Voice", 
		"15": "Companions", 
		"2": "Miscellaneous", 
		"21": "Weapons", 
		"22": "Armour", 
		"3": "Portraits", 
		"4": "Visuals and Graphics", 
		"5": "Overhauls", 
		"7": "Utilities", 
		"8": "User Interface", 
		"9": "ReShade Preset"
	},
	"masseffect" : {
		"10": "Controls", 
		"3": "Models and Textures", 
		"4": "Miscellaneous", 
		"5": "Saved Games", 
		"6": "Utilities", 
		"7": "Visuals and Graphics", 
		"8": "User Interface", 
		"9": "Gameplay Effects and Changes"
	},
	"mafia2" : {
		"2": "Miscellaneous", 
		"3": "Stories and Missions", 
		"4": "Cars &amp; Vehicles", 
		"5": "Outfits &amp; Clothing"
	},
	"naruto3" : {
		"2": "Miscellaneous", 
		"3": "Character Swap", 
		"4": "Gameplay", 
		"5": "Models and Textures"
	},
	"neverwinter" : {
		"22": "Characters", 
		"23": "Creatures", 
		"24": "Hakpaks", 
		"25": "Models", 
		"26": "Modules", 
		"27": "Videos and trailers", 
		"28": "Miscellaneous", 
		"29": "Prefabs", 
		"30": "Portraits", 
		"31": "Scripts", 
		"32": "Sounds", 
		"33": "Textures", 
		"34": "User Interface", 
		"35": "Utilities", 
		"36": "Weapons", 
		"37": "Persistent Worlds", 
		"38": "Armour and Clothing"
	},
	"enderal" : {
		"106": "Miscellaneous", 
		"107": "Player Homes", 
		"108": "Cheats and God items", 
		"109": "User Interface", 
		"110": "Bug Fixes", 
		"111": "Armour", 
		"112": "Weapons", 
		"113": "Spells &amp; Enchantments", 
		"114": "Modding Tools and Utilities", 
		"115": "Audio", 
		"116": "Creatures", 
		"117": "Followers and Companions", 
		"118": "Crafting"
	},
	"derailvalley" : {
		"2": "Miscellaneous", 
		"3": "Models and Textures", 
		"4": "Utilities", 
		"5": "Scripts", 
		"6": "Gameplay Effects and Changes", 
		"7": "User Interface"
	},
	"pathfinderkingmaker" : {
		"10": "New Content", 
		"2": "Miscellaneous", 
		"3": "Portraits", 
		"4": "Audio", 
		"5": "Cheats", 
		"6": "Quality of Life", 
		"7": "Utilities", 
		"8": "Saved game", 
		"9": "Gameplay Effects and Changes"
	},
	"farcry3" : {
		"10": "Compilations", 
		"11": "Crafting", 
		"12": "Maps", 
		"13": "Maps (Xbox 360 Showcase)",
		"14": "Gameplay Changes", 
		"15": "Cheats", 
		"16": "Graphics", 
		"17": "Saved games", 
		"18": "Outfits", 
		"19": "Maps (SP)",
		"2": "User Interface", 
		"20": "Maps (SP/MP)",
		"21": "Maps (MP)",
		"3": "Miscellaneous", 
		"4": "Weapons", 
		"5": "Bug Fixes", 
		"6": "Utilities", 
		"7": "AI", 
		"8": "Textures", 
		"9": "Configs"
	},
	"trialsofmana" : {
		"2": "Miscellaneous", 
		"3": "Gameplay", 
		"4": "Models", 
		"5": "Visual Presets", 
		"6": "Audio"
	},
	"borderlands3" : {
		"2": "Miscellaneous", 
		"3": "Saved Games", 
		"4": "Cheats and God items", 
		"5": "Audio", 
		"6": "Visuals and Graphics"
	},
	"batmanarkhamcity" : {
		"2": "Miscellaneous", 
		"3": "Skins"
	},
	"totalwarthreekingdoms" : {
		"2": "Miscellaneous", 
		"3": "Gameplay Effects and Changes", 
		"4": "Fixes", 
		"5": "Saved Games", 
		"6": "Units", 
		"7": "Characters"
	},
	"spyroreignitedtrilogy" : {
		"10": "Effects", 
		"4": "Miscellaneous", 
		"5": "Visual Presets", 
		"6": "Audio and SFX", 
		"7": "UI/Dialogue", 
		"8": "Player Skins", 
		"9": "Model Changes"
	},
	"rebelgalaxyoutlaw" : {
		"2": "Miscellaneous", 
		"3": "Paint jobs", 
		"4": "Audio", 
		"5": "Stencils"
	},
	"outward" : {
		"2": "Miscellaneous", 
		"3": "Gameplay Effects and Changes", 
		"4": "ReShade Presets", 
		"5": "Models and Textures", 
		"6": "Cheats", 
		"7": "Utilities", 
		"8": "User Interface", 
		"9": "Modders Resources and Tutorials"
	},
	"finalfantasy12" : {
		"2": "Miscellaneous"
	},
	"mirrorsedgecatalyst" : {
		"10": "Bug Fixes", 
		"12": "Cheats", 
		"2": "Miscellaneous", 
		"3": "Audio", 
		"4": "Models and Textures", 
		"5": "Gameplay Effects and Changes", 
		"6": "Modders Resources and Tutorials", 
		"7": "ReShade Presets", 
		"8": "User Interface", 
		"9": "Graphics and Effects"
	},
	"finalfantasy15" : {
		"2": "Miscellaneous", 
		"3": "Reshades"
	},
	"legendofgrimrock2" : {
		"2": "Miscellaneous", 
		"3": "Dungeons", 
		"4": "Items", 
		"5": "Portraits", 
		"6": "Tileset", 
		"7": "Tools and utilities"
	},
	"vampirebloodlines" : {
		"10": "Modders Resources and Tutorials", 
		"11": "Quests", 
		"2": "Miscellaneous", 
		"3": "Armour", 
		"4": "Audio - Sounds", 
		"5": "User Interface", 
		"6": "Visuals and Graphics", 
		"7": "Models and Textures", 
		"8": "Audio - Music", 
		"9": "Utilities"
	},
	"elderscrollsonline" : {
		"10": "Chat and Communication", 
		"11": "Class or Role Specific", 
		"12": "Combat", 
		"13": "Crafting", 
		"14": "Maps and Compasses", 
		"15": "PVP", 
		"16": "Looting", 
		"17": "Quests", 
		"18": "Visuals and Graphics", 
		"19": "Roleplay", 
		"2": "Miscellaneous", 
		"3": "Tools and utilities", 
		"4": "Raiding", 
		"5": "Mail", 
		"6": "Bags, Banks and Inventory", 
		"7": "Auction House, Vendors and Economy", 
		"8": "Action Bar", 
		"9": "Buffs and Debuffs"
	},
	"galacticcivilizations3" : {
		"10": "Star Diversity", 
		"11": "AI ", 
		"12": "Custom Races", 
		"13": "Logos", 
		"14": "Modders Resources and Tutorials", 
		"2": "Miscellaneous", 
		"3": "Visuals and Graphics", 
		"4": "Audio - Misc", 
		"5": "Gameplay Effects and Changes", 
		"6": "Factions", 
		"7": "Maps", 
		"8": "Balancing", 
		"9": "Planetary Improvements"
	},
	"assassinscreedodyssey" : {
		"10": "Saved Games", 
		"2": "Miscellaneous", 
		"4": "Modders Resources and Tutorials", 
		"5": "Outfits", 
		"6": "User Interface", 
		"7": "Utilities", 
		"8": "Visuals and Graphics", 
		"9": "Body, Face and Hair"
	},
	"rugbychallenge3" : {
		"2": "Miscellaneous", 
		"3": "Stadiums", 
		"4": "Strips, Kits &amp; Jerseys"
	},
	"greedfall" : {
		"10": "Weapons, Armour and Clothing", 
		"11": "Visuals and Graphics", 
		"12": "Body, Face, Hair", 
		"13": "Utilities", 
		"2": "Miscellaneous", 
		"3": "Cheats", 
		"6": "Gameplay Effects and Changes", 
		"7": "Audio", 
		"8": "User Interface", 
		"9": "Companions"
	},
	"bloodstainedritualofthenight" : {
		"10": "Animation", 
		"2": "Miscellaneous", 
		"3": "ReShade Preset", 
		"4": "User Interface", 
		"5": "Textures", 
		"6": "Models", 
		"7": "Audio", 
		"8": "Tools and Utilities", 
		"9": "Gameplay Effects and Changes"
	},
	"fallenenchantress" : {
		"102": "Miscellaneous", 
		"112": "Weapon or Armour Sets", 
		"114": "User Interface", 
		"115": "Maps", 
		"116": "Total Conversions", 
		"117": "Bug Fixes", 
		"118": "Gameplay Effects", 
		"119": "Races", 
		"120": "Spells and Magic", 
		"121": "Visuals and graphics", 
		"122": "Creatures and Units", 
		"123": "Professions", 
		"124": "AI", 
		"99": "Utilities and Tools"
	},
	"narutoultimateninjastorm4" : {
		"2": "Miscellaneous", 
		"3": "Visuals and Graphics", 
		"4": "Costumes Swap", 
		"5": "Characters", 
		"6": "Saved Games", 
		"7": "Movesets"
	},
	"shadowrunreturns" : {
		"11": "Textures and Meshes", 
		"13": "Sounds and Music", 
		"15": "Tools", 
		"17": "UI Mods", 
		"19": "Maps", 
		"22": "Tilesets", 
		"24": "Alphas, Betas or Unfinished Work", 
		"25": "Campaign/UGC", 
		"26": "Items", 
		"27": "Tutorial", 
		"28": "Vehicles", 
		"29": "Cheats", 
		"3": "Miscellaneous", 
		"30": "Visuals and Graphics", 
		"5": "Stories", 
		"7": "Props and Scene Assets", 
		"9": "Portraits"
	},
	"skyrimnintendoswitch" : {
		"10": "Armour", 
		"11": "Weapons", 
		"12": "Weapons and Armour", 
		"13": "User Interface", 
		"14": "Overhauls", 
		"15": "Patches", 
		"16": "Player homes", 
		"17": "Quests and Adventures", 
		"18": "Races, Classes, and Birthsigns", 
		"19": "Clothing", 
		"2": "Miscellaneous", 
		"20": "Combat", 
		"21": "Crafting", 
		"22": "Creatures", 
		"23": "Environmental", 
		"24": "Followers &amp; Companions", 
		"25": "Immersion", 
		"26": "Items and Objects - Player", 
		"27": "Items and Objects - World", 
		"28": "Magic - Spells &amp; Enchantments", 
		"29": "Magic - Gameplay", 
		"3": "Animation", 
		"30": "Mercantiles (shops, stores, inns, taverns, etc)",
		"31": "Modders Resources and Tutorials", 
		"32": "NPC", 
		"33": "Audio", 
		"34": "Cheats and God items", 
		"35": "New Lands", 
		"36": "Pets", 
		"4": "Body, Face, and Hair", 
		"5": "Gameplay Effects and Changes", 
		"6": "Models and Textures", 
		"7": "NPC - Children", 
		"8": "Visuals and Graphics", 
		"9": "Utilities"
	},
	"rodina" : {
		"10": "Weapons", 
		"11": "Planets", 
		"12": "NPCs", 
		"2": "Miscellaneous", 
		"3": "Overhauls", 
		"4": "User Interface", 
		"5": "Ships", 
		"6": "Models and Textures", 
		"7": "Visuals and Graphics", 
		"8": "Utilities", 
		"9": "Ship Interiors"
	},
	"divinityoriginalsin" : {
		"10": "Music", 
		"11": "Creatures", 
		"12": "Overhauls", 
		"13": "Quests and Adventures", 
		"15": "Models and Textures", 
		"16": "Campaigns", 
		"17": "Audio", 
		"18": "Skills", 
		"2": "Miscellaneous", 
		"3": "Armor", 
		"4": "Clothing", 
		"5": "Crafting", 
		"6": "Gameplay", 
		"7": "Hair/Faces", 
		"8": "UI", 
		"9": "Companions"
	},
	"finalfantasyxx2hdremaster" : {
		"2": "Miscellaneous"
	},
	"southparkthestickoftruth" : {
		"2": "Miscellaneous"
	},
	"daggerfallunity" : {
		"10": "Models and Textures", 
		"11": "Overhauls", 
		"12": "User Interface", 
		"13": "Utilities", 
		"2": "Miscellaneous", 
		"4": "Quests", 
		"5": "Audio", 
		"6": "Guilds and Factions", 
		"7": "New Locations", 
		"8": "Gameplay Effects and Changes", 
		"9": "Modders Resources and Tutorials"
	},
	"civilisationvi" : {
		"2": "Miscellaneous"
	},
	"planetzoo" : {
		"2": "Miscellaneous", 
		"3": "Animals", 
		"4": "Objects - Structures, Walls, and Clutter", 
		"5": "Objects - Habitat", 
		"6": "Objects - Environment", 
		"7": "User Interface", 
		"8": "Visuals and Graphics"
	},
	"batmanarkhamorigins" : {
		"2": "Miscellaneous", 
		"3": "Skins", 
		"4": "User Interface"
	},
	"dragonquestxi" : {
		"4": "Miscellaneous", 
		"5": "Textures", 
		"6": "User Interface"
	},
	"starwarsempireatwar" : {
		"13": "Demo Tools", 
		"2": "Miscellaneous", 
		"5": "Demo Mods", 
		"6": "FoC Mods"
	},
	"farmingsimulator19" : {
		"10": "Maps", 
		"14": "Placeables and Consumables", 
		"15": "Tools", 
		"16": "Graphics and Textures", 
		"4": "Miscellaneous", 
		"5": "Scripts", 
		"6": "Vehicles"
	},
	"survivingmars" : {
		"6": "Miscellaneous", 
		"7": "Buildings", 
		"8": "Gameplay", 
		"9": "Events"
	},
	"payday2" : {
		"10": "Cheats", 
		"11": "Gameplay", 
		"12": "ReShade Preset", 
		"13": "Scripts", 
		"14": "Visuals and Graphics", 
		"2": "Miscellaneous", 
		"3": "Animations", 
		"4": "Models and Textures", 
		"6": "Audio - SFX", 
		"7": "Audio - Music", 
		"8": "User Interface", 
		"9": "Utilities"
	}
}